### ISSUE TITLE
New Plugin: pdm-bump

### ISSUE THREAD

**Issue by carstencodes** [pdm-project/awesome-pdm#1]
Hi, 

I just released a version configuration plugin for PDM, called pdm-bump, which is inspired by tools like bump2version.

You can find it here: https://github.com/carstencodes/pdm-bump

I'd be happy if you add the plugin to the list of plugins in your collection.

Regards

Carsten

**Comment by frostming** [comment]
Sure, go ahead with a PR. BTW, how is your experience with the plugin API?

**Comment by carstencodes** [comment]
@frostming Thanks, I'll do it this afternoon. 

I'm sorry for the delay, but I was sick for a long time and I'm still recovering.

According to your comment on my experience: I have some issues testing my plugins locally before publishing the final wheel. Please see [pdm#878](https://github.com/pdm-project/pdm/issues/878) for details.

I also have an idea for creating a bill-of-materials plug-in that produces reports like in pip-licenses. Hence I have to read/parse the package tree. I currently have to re-engineer this from existing functions.

Is there any public API documentation available on APIs that are available to the plug-ins? I'm currently stuck.
